# Generated by Django 6.0 on 2026-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
